language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS="-I/usr/include/x86_64-linux-gnu/c++/4.8/" -DBUILD_TESTS=1 -DENABLE_GCOVERALLS=1 .. && make && ldd liblogging-test* && ctest --output-on-failure -R ^liblogging-test && ./coveralls-upload
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ raring main universe"
  - sudo add-apt-repository -y "deb http://llvm.org/apt/raring/ llvm-toolchain-raring main"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 libstdc++-4.8-dev clang-3.3 libboost1.53-all-dev
  - sudo update-alternatives --quiet --install /usr/bin/gcc  gcc  /usr/bin/gcc-4.6  60
                                     --slave   /usr/bin/g++  g++  /usr/bin/g++-4.6
                                     --slave   /usr/bin/gcov gcov /usr/bin/gcov-4.6
  - sudo update-alternatives --quiet --install /usr/bin/gcc  gcc  /usr/bin/gcc-4.8  60
                                     --slave   /usr/bin/g++  g++  /usr/bin/g++-4.8
                                     --slave   /usr/bin/gcov gcov /usr/bin/gcov-4.8
  - sudo update-alternatives --quiet --set gcc /usr/bin/gcc-4.8
